### ISSUE TITLE
Change default docker registry into docker.io for charts

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere-sigs/ks-devops#61]
Currently, the default docker registry of ks-devops charts is `ghcr.io`, which is too slow if you are in Chinese network.

See also: https://github.com/kubesphere-sigs/ks-devops/blob/678147e3ae80f3f12370ee743c03d2041f212864/charts/ks-devops/values.yaml

### Suggestions

Change the default docker registry from `ghcr.io` into `docker.io`.

/good-first-issue

**Comment by LinuxSuRen** [comment]
hi @JohnNiang , as you mentioned. The connection with `ghcr.io` is slow. I didn't know how do you get the result. Perhaps you test it from a server located in China. But what about other countries? Our community focus on the global world instead of one country. So, I don't think this is not good enough to change the default option. Please try to answer the following questions:

* connection speed data (`ghcrd.io` and `docker.io`) from all over the world
  * maybe @AbdelouahabMbarki could tell us the speed of them from his location
* other pros and cons

## Open question
As far as I know, `docker.io` has the limitation of the pull request. But `ghcr.io` does not have. So, what is the solution if users reach the limitation?

## Potential solution
It's possible to support multiple container registries in the helm chart. As we can see from the [values.yaml](https://github.com/kubesphere-sigs/ks-devops/blob/678147e3ae80f3f12370ee743c03d2041f212864/charts/ks-devops/values.yaml#L3) file. We can add a new variable for the host of the container registry. For example:

```
image:
  registry: ghcr.io/kubesphere-sigs
  controller:
    repository: devops-controller
    tag: master
```

So, we can change the container registry like this: `helm install xxxx -s image.registry=docker.io/kubespheresig`

### Potential actions
* add a new value as I suggested
* change the references of the image path
* add instructions about how to use the new feature in the document

**Comment by AbdelouahabMbarki** [comment]
i did a  benchmark from 3 servers located  in 3 different region  over the world in my case i use the Europe region  , here is the result of benchmark : 
```
**Europe (Paris)**
| Pulling image from ghcr.io
16:22:57.628|eu-west-3|ks-devops-plugin-apiserver:sha-3435d58|ghcr.io || TIME-BENCHMARK :
0:02.82 real,0.02 user,0.01 sys
| Pulling image from docker.io
16:23:00.597|eu-west-3|ks-devops-plugin-apiserver:sha-3435d58|docker.io || TIME-BENCHMARK :
0:04.05 real,0.03 user,0.01 sys

**US East (N. Virginia)**
| Pulling image from ghcr.io
16:31:29.090|us-east-1|ks-devops-plugin-apiserver:sha-3435d58|ghcr.io || TIME-BENCHMARK :
0:02.51 real,0.03 user,0.00 sys
| Pulling image from docker.io
16:31:31.809|us-east-1|ks-devops-plugin-apiserver:sha-3435d58|docker.io || TIME-BENCHMARK :
0:02.29 real,0.02 user,0.02 sys

**Asia Pacific (Tokyo)**
| Pulling image from ghcr.io
16:57:23.849|ap-northeast-1|ks-devops-plugin-apiserver:sha-3435d58|ghcr.io || TIME-BENCHMARK :
0:03.62 real,0.02 user,0.01 sys
| Pulling image from docker.io
16:57:27.610|ap-northeast-1|ks-devops-plugin-apiserver:sha-3435d58|docker.io || TIME-BENCHMARK :
0:05.46 real,0.03 user,0.01 sys
```

**Comment by AbdelouahabMbarki** [comment]
@LinuxSuRen  there is no much of a big difference between the speed of the  two in my situation .

**Comment by LinuxSuRen** [comment]
hi @AbdelouahabMbarki , it's wonderful, and thanks very much for the benchmark tests. It looks like that `ghcr.io` and `docker.io` have similar speed in some big cities which outside of China.

As I mentioned, we can support multiple image registries. @JohnNiang do you think it's reasonable to push the multiple registries feature forward?

**Comment by shihaoH** [comment]
What registries are currently available?

**Comment by LinuxSuRen** [comment]
The are `kubespheresig/devops-apiserver` and `ghcr.io/kubesphere-sigs/devops-tools`

**Comment by shihaoH** [comment]
```
image:
  # support 'ghcr.io/kubesphere-sigs' or 'kubespheresig'
  registry: kubespheresig
  controller:
    repository: devops-controller
    tag: master
  apiserver:
    repository: devops-apiserver
    tag: master
  tools:
    repository: devops-tools
    tag: master
  pullPolicy: IfNotPresent
```

**Comment by JohnNiang** [comment]
Hi @shihaoH , if you want to get it done, please assign yourself by commenting `/assign`.

**Comment by shihaoH** [comment]
```
Failed to pull image "kubespheresig/devops-tools:master": rpc error: code = Unknown desc = error pulling image configuration: Get https://registry-1.docker.io/v2/kubespheresig/devops-tools/blobs/sha256:e1feaccdebb29406d03920cc496e2fccded6e7d49c21e7870651179d85f113ea: read tcp 10.120.82.25:48806->3.229.227.53:443: read: connection reset by peer
```

**Comment by LinuxSuRen** [comment]
> kubespheresig/devops-tools

It does exist. Please see also https://hub.docker.com/r/kubespheresig/devops-tools/tags?page=1&ordering=last_updated

**Comment by JohnNiang** [comment]
> ```
> Failed to pull image "kubespheresig/devops-tools:master": rpc error: code = Unknown desc = error pulling image configuration: Get https://registry-1.docker.io/v2/kubespheresig/devops-tools/blobs/sha256:e1feaccdebb29406d03920cc496e2fccded6e7d49c21e7870651179d85f113ea: read tcp 10.120.82.25:48806->3.229.227.53:443: read: connection reset by peer
> ```

`docker.io` registry is unstable in China recently.

**Comment by shihaoH** [comment]
docker daemon config `"registry-mirrors": ["https://scybvk1f.mirror.aliyuncs.com"]`
and i exec `docker pull kubespheresig/devops-tools:master` to successfully pull
